name: CI | Upload R2

on:
  workflow_run:
    workflows: [ "CI | Pack - Pull Request" ]
    types: [ completed ]

permissions:
  actions: read

jobs:
  r2-uplaod:
    name: Upload R2
    runs-on: ubuntu-latest
    if: |
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success' &&
      github.repository == 'TeamKugimiya/ModsTranslationPack'

    steps:
      - name: Setup s3cmd
        uses: s3-actions/s3cmd@v2.0.0
        with:
          provider: cloudflare
          account_id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          access_key: ${{ secrets.CLOUDFLARE_R2_ACCESS_KEY_ID }}
          secret_key: ${{ secrets.CLOUDFLARE_R2_SECRET_ACCESS_KEY }}

      - name: Get the PR number
        id: get-pr-number
        run: |
          PR_RAW=$(curl 'https://api.github.com/search/issues?q=${{ github.event.workflow_run.head_commit.id }}')
          PR_NUM=$(echo $PR_RAW | jq '.items | map(select(.repository_url=="https://api.github.com/repos/${{ github.repository }}")) | .[0].number')
          echo "PR_NUM=${PR_NUM}" >> ${GITHUB_OUTPUT}

      - name: Download All ModsTranslationPack Artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v9
        with:
          name: ModsTranslationPack-[0-9]+\.[0-9]+\.x
          run_id: ${{ github.event.workflow_run.id }}
          name_is_regexp: true

      - name: Move Artifact Files
        run: |
          for i in ModsTranslationPack-*
          do
            cd "$i" || exit 1
            sha256sum -c checksum.txt
            mv ModsTranslationPack-*.zip ../
            cd ..
          done
          ls -alh 

      - name: Upload to R2
        run: |
          s3cmd put *.zip s3://${{ secrets.CLOUDFLARE_R2_BUCKET }}/modstranslationpack/pr/${{ steps.get-pr-number.outputs.PR_NUM }}/
